# Cafaye lazygit Defaults
# ═══════════════════════════════════════════════════════════════════

gui:
  showIcons: true
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1"  # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4"  # Text
    optionsTextColor:
      - "#89b4fa"  # Blue
    selectedLineBgColor:
      - "#313244"  # Surface0
    selectedRangeBgColor:
      - "#313244"  # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5"  # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa"  # Blue
    unstagedChangesColor:
      - red

customCommands:
  - key: "<c-p>"
    description: "Create a pull request on Github"
    command: "gh pr create --fill --web"
    context: "global"
    loadingText: "Creating pull request on GitHub"
  - key: "E"
    description: "Add empty commit"
    context: "commits"
    command: 'git commit --allow-empty -m "empty commit"'
    loadingText: "Committing empty commit..."
